# Generated by Django 6.0.7 on 2026-08-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
