# Generated by Django 6.0.7 on 2026-08-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_rename_create_at_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
